//
// Created by hezza on 8/5/2023.
//

#ifndef BJARNESTROUSTRUPPROGRAMMINGPRINCIPLESANDPRACTICE_LIBRARY_H
#define BJARNESTROUSTRUPPROGRAMMINGPRINCIPLESANDPRACTICE_LIBRARY_H


class Library {

};


#endif //BJARNESTROUSTRUPPROGRAMMINGPRINCIPLESANDPRACTICE_LIBRARY_H
